// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDl0XUTLXO5T0NgQX0iQe2LFfLdmjUjt0',
    appId: '1:576716959045:web:1bd3e59b4b16c02c6b3a87',
    messagingSenderId: '576716959045',
    projectId: 'bio-track-de846',
    authDomain: 'bio-track-de846.firebaseapp.com',
    databaseURL: 'https://bio-track-de846-default-rtdb.firebaseio.com',
    storageBucket: 'bio-track-de846.appspot.com',
    measurementId: 'G-6R1NK7YM5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-hR5VlFqSJ4j9mxJphf9V1NXMRJfZCRE',
    appId: '1:576716959045:android:e8f0b5d6c7e3a1b86b3a87',
    messagingSenderId: '576716959045',
    projectId: 'bio-track-de846',
    databaseURL: 'https://bio-track-de846-default-rtdb.firebaseio.com',
    storageBucket: 'bio-track-de846.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKJrGvs4G-hP8u6C7qN4s5mOxWRtYvBzE',
    appId: '1:576716959045:ios:a2c3e4f5b6d7e8f96b3a87',
    messagingSenderId: '576716959045',
    projectId: 'bio-track-de846',
    databaseURL: 'https://bio-track-de846-default-rtdb.firebaseio.com',
    storageBucket: 'bio-track-de846.appspot.com',
    iosBundleId: 'com.example.gp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKJrGvs4G-hP8u6C7qN4s5mOxWRtYvBzE',
    appId: '1:576716959045:ios:a2c3e4f5b6d7e8f96b3a87',
    messagingSenderId: '576716959045',
    projectId: 'bio-track-de846',
    databaseURL: 'https://bio-track-de846-default-rtdb.firebaseio.com',
    storageBucket: 'bio-track-de846.appspot.com',
    iosBundleId: 'com.example.gp',
  );
}
